[project]
name = "sim-caso"
version = "0.1.0"
description = "CodificaciÃ³n en Ansible"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=13.0.0",
    "ansible-pylibssh>=1.3.0",
]
